// Generated by CodeAssist from the project model. Review before you rely on it.

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "com.Cali.droidlens"
    compileSdk = 36

    defaultConfig {
        minSdk = 26
        targetSdk = 36
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11)
    }
}

dependencies {
    implementation("com.google.android.material:material:1.12.0")
    implementation("org.slf4j:slf4j-nop:2.0.9")
    implementation("io.github.skylot:jadx-dex-input:1.4.7") {
        exclude(group = "io.github.skylot", module = "jadx-core")
    }
    implementation("io.github.skylot:jadx-core:1.4.7")
}
